sudo: required
services:
  - docker

before_install:
  - docker built -t rootfaheem/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rootfaheem/client-test yarn test -- --eoverage

after_success:
  - docker build -t rootfaheem/multi-client ./client
  - docker build -t rootfaheem/multi-server ./server
  - docker build -t rootfaheem/multi-nginx ./nginx
  - docker build -t rootfaheem/multi-worker ./worker
