sudo: required
services:
  - docker

before_install:
  - echo "BEFORE INSTALL START"

#   - docker build -t rootfaheem/client-test -f ./client/Dockerfile.dev ./client

script:
  - echo "SCRIPT RAN SUCCESSFULLY"
#   - docker run rootfaheem/client-test yarn test -- --eoverage

after_success:
  - docker build -t rootfaheem/multi-client ./client
  - docker build -t rootfaheem/multi-server ./server
  - docker build -t rootfaheem/multi-nginx ./nginx
  - docker build -t rootfaheem/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take docker images and push those images
  - docker push rootfaheem/multi-client
  - docker push rootfaheem/multi-server
  - docker push rootfaheem/multi-nginx
  - docker push rootfaheem/multi-worker
